# -*- coding: utf-8 -*-
"""mlmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yp0ROQfis1X8nG0UZBIV7Bz3QI8OhNGb
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import pickle

data = pd.read_csv('Crop_recommendation.csv')
data.head()

data.shape

#split features and labels
x = data.iloc[:,:-1]#features
y= data.iloc[:,-1]#labels

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)
model=RandomForestClassifier()

model.fit(x_train,y_train)
pickle.dump(model,open('model.pkl','wb'))

predictions=model.predict(x_test)

accuracy = model.score(x_test, y_test)
print(f"Accuracy:",accuracy)

new_features = [[36,58,25,28.66024,59.31891,8.399136,36.9263]]
predicted_crop = model.predict(new_features)
print("Predicted Crop:", predicted_crop)

